---
hero_image: images/banner.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Space Age
description: Find out how old you'd be if you lived on another planet.
original_url: https://codeclubprojects.org/en-GB/space-mission/space-age
interests: ''
technologies: ''
site_areas: codeclub, space-mission
steps:
- title: Introduction
- title: Storing your age
- title: Your age on Mercury
- title: Travel to Mercury
- title: 'Challenge: Age on other planets'
- title: 'Challenge: Age accuracy'

